### ISSUE TITLE
[ 10.2.300 ] App.BOLEntry.BOLForm Cast Exception

### ISSUE THREAD

**Issue by hasokeric** [josegomez/epicor-editor-helper#1]
When Launching the BOLForm it throws an exception of
 Unable to cast object of type 'Ice.Lib.Framework.EpiTransaction' to type 'Erp.UI.App.BOLEntry.Transaction'.

```
Got in the Function
Customization Verify
Got Epicor DLL
Finding File
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Ice.Lib.Framework.EpiTransaction' to type 'Erp.UI.App.BOLEntry.Transaction'.
   at Erp.UI.App.BOLEntry.BOLForm..ctor(EpiTransaction iTrans)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at CustomizationEditor.Program.DownloadAndSync(Session epiSession, CommandLineParams o) in C:\Users\jose\source\repos\CustomizationEditor\CommonCode\Program.cs:line 390
```

**Comment by josegomez** [comment]
Resolved on latest Helper Push
